Document: developer-debug-display
Title: Debian developer-debug-display Manual
Author: <insert document author here>
Abstract: This manual describes what developer-debug-display is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/developer-debug-display/developer-debug-display.sgml.gz

Format: postscript
Files: /usr/share/doc/developer-debug-display/developer-debug-display.ps.gz

Format: text
Files: /usr/share/doc/developer-debug-display/developer-debug-display.text.gz

Format: HTML
Index: /usr/share/doc/developer-debug-display/html/index.html
Files: /usr/share/doc/developer-debug-display/html/*.html
